version: '3.7'
services:
    db:
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - 5438:5432
        volumes: 
          - postgres-data:/var/lib/postgresql/data
    api_vectors_service:
        container_name: api_vectors 
        build: ./api
        #image: api_get_vector_from_audio:latest
        environment:
            - index_path=/home/mnt/g/PYTHON_MAIN_G/speaker_identification/index/hnswlib.index
        depends_on:
            - db
        command: uvicorn app_:app --host 0.0.0.0 --app-dir /opt/project2/
        volumes:
            - /:/home

        ports:
            - 8006:8000
volumes:
  postgres-data: